services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://root:root@mongodb:27017/
      DATA_DIR: /data
    env_file:
      - path: ./.env
        required: true
    volumes:
      - data:/data
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  data: